name: Terraform Checks

on:
  pull_request:
    branches: [main]
  workflow_dispatch: 

jobs:
  build:
    name: Terraform Validations
    runs-on: ubuntu-latest

    steps:
    #run basic hello world
    - name: Echo Terraform
      run: echo hello terraform world
